[package]
name = "linear"
<<<<<<< HEAD
version = "0.2.0"
=======
version = "0.2.0"
>>>>>>> generics
authors = ["Jonatas <jbmagalhaes28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
